# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            UncleChen
description:      'Welcome to unclechen's blog, hope you enjoy my pages.'
url:              http://unclechen.github.io
baseurl:          /
logo:             /content/img/me.jpg

author:
  name:           'Chen Xihong'
  url:            https://github.com/unclechen

paginate:         5

github:
  repo:           https://github.com/unclechen/uncleche.github.io

disqus_shortname: unclechen

gems:
  - jekyll-sitemap

twitter: '@nought'