# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Uncle Chen
description:      'This is my personal blog and any views expressed here are mine. Wish we can make something different.  ---I can do all the things.'
url:              http://unclechen.github.io
baseurl:          /
logo:             /content/images/me.jpg

author:
  name:           'Chen Xihong'
  url:            https://github.com/unclechen

paginate:         5

disqus_shortname: unclechen

github:
  repo:           https://github.com/unclechen/uncleche.github.io

gems:
  - jekyll-sitemap

twitter: '@unclechen'

kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  input: GFM